---
apiVersion: v1
kind: Service
metadata:
  name: mc-server
spec:
  type: NodePort
  ports:
  - name: server-port
    port: 25565
    protocol: TCP
    nodePort: {{ mc_server.port }}
    targetPort: 25565
  selector:
    app: mc-server